alter table EKOMERP_LOCATION add constraint FK_EKOMERP_LOCATION_STOCKMAN foreign key (STOCKMAN_ID) references SEC_USER(ID);
create index IDX_EKOMERP_LOCATION_STOCKMAN on EKOMERP_LOCATION (STOCKMAN_ID);
