alter table EKOMERP_PRODUCT add constraint FK_EKOMERP_PRODUCT_UNIT foreign key (UNIT_ID) references EKOMERP_UNIT(ID);
alter table EKOMERP_PRODUCT add constraint FK_EKOMERP_PRODUCT_CATEGORY foreign key (CATEGORY_ID) references EKOMERP_CATEGORY(ID);
create index IDX_EKOMERP_PRODUCT_CATEGORY on EKOMERP_PRODUCT (CATEGORY_ID);
create index IDX_EKOMERP_PRODUCT_UNIT on EKOMERP_PRODUCT (UNIT_ID);
