alter table EKOMERP_INVENTORY_QUANTITY add constraint FK_EKOMERP_INVENTORY_QUANTITY_LOCATION foreign key (LOCATION_ID) references EKOMERP_LOCATION(ID);
alter table EKOMERP_INVENTORY_QUANTITY add constraint FK_EKOMERP_INVENTORY_QUANTITY_PRODUCT foreign key (PRODUCT_ID) references EKOMERP_PRODUCT(ID);
create index IDX_EKOMERP_INVENTORY_QUANTITY_LOCATION on EKOMERP_INVENTORY_QUANTITY (LOCATION_ID);
create index IDX_EKOMERP_INVENTORY_QUANTITY_PRODUCT on EKOMERP_INVENTORY_QUANTITY (PRODUCT_ID);
