alter table EKOMERP_PARTNER add constraint FK_EKOMERP_PARTNER_IMAGE foreign key (IMAGE_ID) references SYS_FILE(ID);
alter table EKOMERP_PARTNER add constraint FK_EKOMERP_PARTNER_PARENT foreign key (PARENT_ID) references EKOMERP_PARTNER(ID);
create unique index IDX_EKOMERP_PARTNER_UNIQ_NAME on EKOMERP_PARTNER (NAME, DELETE_TS) ;
create index IDX_EKOMERP_PARTNER_IMAGE on EKOMERP_PARTNER (IMAGE_ID);
create index IDX_EKOMERP_PARTNER_PARENT on EKOMERP_PARTNER (PARENT_ID);
