alter table EKOMERP_PURCHASE_ORDER add constraint FK_EKOMERP_PURCHASE_ORDER_VENDOR foreign key (VENDOR_ID) references EKOMERP_PARTNER(ID);
create index IDX_EKOMERP_PURCHASE_ORDER_VENDOR on EKOMERP_PURCHASE_ORDER (VENDOR_ID);
