alter table EKOMERP_INVOICE add constraint FK_EKOMERP_INVOICE_PARTNER foreign key (PARTNER_ID) references EKOMERP_PARTNER(ID);
create index IDX_EKOMERP_INVOICE_PARTNER on EKOMERP_INVOICE (PARTNER_ID);
