alter table EKOMERP_INVOICE_LINE add constraint FK_EKOMERP_INVOICE_LINE_PRODUCT foreign key (PRODUCT_ID) references EKOMERP_PRODUCT(ID);
alter table EKOMERP_INVOICE_LINE add constraint FK_EKOMERP_INVOICE_LINE_INVOICE foreign key (INVOICE_ID) references EKOMERP_INVOICE(ID);
create index IDX_EKOMERP_INVOICE_LINE_INVOICE on EKOMERP_INVOICE_LINE (INVOICE_ID);
create index IDX_EKOMERP_INVOICE_LINE_PRODUCT on EKOMERP_INVOICE_LINE (PRODUCT_ID);
