alter table EKOMERP_CALCULATION add constraint FK_EKOMERP_CALCULATION_PRODUCT foreign key (PRODUCT_ID) references EKOMERP_PRODUCT(ID);
create index IDX_EKOMERP_CALCULATION_PRODUCT on EKOMERP_CALCULATION (PRODUCT_ID);
