alter table EKOMERP_PRODUCT_PRICE add constraint FK_EKOMERP_PRODUCT_PRICE_PRODUCT foreign key (PRODUCT_ID) references EKOMERP_PRODUCT(ID);
alter table EKOMERP_PRODUCT_PRICE add constraint FK_EKOMERP_PRODUCT_PRICE_PRICING_TYPE foreign key (PRICING_TYPE_ID) references EKOMERP_PRICING_TYPE(ID);
create index IDX_EKOMERP_PRODUCT_PRICE_PRODUCT on EKOMERP_PRODUCT_PRICE (PRODUCT_ID);
create index IDX_EKOMERP_PRODUCT_PRICE_PRICING_TYPE on EKOMERP_PRODUCT_PRICE (PRICING_TYPE_ID);
