alter table EKOMERP_CALCULATION drop column SELLING_PRICE_TOTAL ;
alter table EKOMERP_CALCULATION add SELLING_PRICE_TOTAL decimal(19, 2) ;
alter table EKOMERP_CALCULATION drop column AMOUNT_TAX ;
alter table EKOMERP_CALCULATION add AMOUNT_TAX decimal(19, 2) ;
alter table EKOMERP_CALCULATION drop column SELLING_PRICE_UNTAXED ;
alter table EKOMERP_CALCULATION add SELLING_PRICE_UNTAXED decimal(19, 2) ;
alter table EKOMERP_CALCULATION drop column PROFIT ;
alter table EKOMERP_CALCULATION add PROFIT decimal(19, 2) ;
alter table EKOMERP_CALCULATION drop column COST_PRICE ;
alter table EKOMERP_CALCULATION add COST_PRICE decimal(19, 2) ;
alter table EKOMERP_CALCULATION drop column FSZN_RATE ;
alter table EKOMERP_CALCULATION add FSZN_RATE decimal(19, 2) ;
alter table EKOMERP_CALCULATION drop column BGS_RATE ;
alter table EKOMERP_CALCULATION add BGS_RATE decimal(19, 2) ;
