alter table EKOMERP_INVOICE add constraint FK_EKOMERP_INVOICE_INVOICE_FILE foreign key (INVOICE_FILE_ID) references SYS_FILE(ID);
create index IDX_EKOMERP_INVOICE_INVOICE_FILE on EKOMERP_INVOICE (INVOICE_FILE_ID);
