alter table EKOMERP_PAYMENT add constraint FK_EKOMERP_PAYMENT_INVOICE foreign key (INVOICE_ID) references EKOMERP_INVOICE(ID);
create index IDX_EKOMERP_PAYMENT_INVOICE on EKOMERP_PAYMENT (INVOICE_ID);
