alter table EKOMERP_GAUGING add constraint FK_EKOMERP_GAUGING_PARTNER foreign key (PARTNER_ID) references EKOMERP_PARTNER(ID);
create index IDX_EKOMERP_GAUGING_PARTNER on EKOMERP_GAUGING (PARTNER_ID);
