alter table EKOMERP_DOOR_ORDER add constraint FK_EKOMERP_DOOR_ORDER_PARTNER foreign key (PARTNER_ID) references EKOMERP_PARTNER(ID);
alter table EKOMERP_DOOR_ORDER add constraint FK_EKOMERP_DOOR_ORDER_DOOR foreign key (DOOR_ID) references EKOMERP_DOOR(ID);
create index IDX_EKOMERP_DOOR_ORDER_PARTNER on EKOMERP_DOOR_ORDER (PARTNER_ID);
create index IDX_EKOMERP_DOOR_ORDER_DOOR on EKOMERP_DOOR_ORDER (DOOR_ID);
