alter table EKOMERP_PURCHASE_ORDER add constraint FK_EKOMERP_PURCHASE_ORDER_INVOICE_FILE foreign key (INVOICE_FILE_ID) references SYS_FILE(ID);
create index IDX_EKOMERP_PURCHASE_ORDER_INVOICE_FILE on EKOMERP_PURCHASE_ORDER (INVOICE_FILE_ID);
