create table EKOMERP_DOOR_ORDER (
    ID uniqueidentifier,
    VERSION integer not null,
    CREATE_TS datetime2,
    CREATED_BY varchar(50),
    UPDATE_TS datetime2,
    UPDATED_BY varchar(50),
    DELETE_TS datetime2,
    DELETED_BY varchar(50),
    --
    NUMBER_ varchar(255) not null,
    DATE_ datetime2,
    PARTNER_ID uniqueidentifier not null,
    MANUFACTURE_DATE datetime2,
    PLACEMENT_CATEGORY decimal(19) not null,
    DOOR_ID uniqueidentifier not null,
    PRICE decimal(19, 2),
    HEIGHT decimal(19, 2) not null,
    WIDTH decimal(19, 2) not null,
    OPENING integer not null,
    NOTES varchar(max),
    ISOLATION_ tinyint,
    PEEPHOLE tinyint,
    TRIM_ tinyint,
    DISMANTILING tinyint,
    LOOP_NUMBER varchar(255) not null,
    TOP_LOCK varchar(255),
    BUTTOMLOCK varchar(255),
    TOP_ONLAY varchar(255),
    BUTTOM_ONLAY varchar(255),
    HANDLE varchar(255),
    CYLINDER varchar(255),
    INTERNAL_DECORATION varchar(max),
    EXTERNAL_DECORATION varchar(max),
    STATUS integer not null,
    MASTER integer,
    PAYED tinyint,
    --
    primary key nonclustered (ID)
);
