alter table EKOMERP_GAUGING add constraint FK_EKOMERP_GAUGING_DOOR_ORDER foreign key (DOOR_ORDER_ID) references EKOMERP_DOOR_ORDER(ID);
create index IDX_EKOMERP_GAUGING_DOOR_ORDER on EKOMERP_GAUGING (DOOR_ORDER_ID);
