-- begin EKOMERP_PRODUCT
alter table EKOMERP_PRODUCT add constraint FK_EKOMERP_PRODUCT_UNIT foreign key (UNIT_ID) references EKOMERP_UNIT(ID)^
alter table EKOMERP_PRODUCT add constraint FK_EKOMERP_PRODUCT_CATEGORY foreign key (CATEGORY_ID) references EKOMERP_CATEGORY(ID)^
alter table EKOMERP_PRODUCT add constraint FK_EKOMERP_PRODUCT_IMAGE foreign key (IMAGE_ID) references SYS_FILE(ID)^
create index IDX_EKOMERP_PRODUCT_CATEGORY on EKOMERP_PRODUCT (CATEGORY_ID)^
create index IDX_EKOMERP_PRODUCT_UNIT on EKOMERP_PRODUCT (UNIT_ID)^
create index IDX_EKOMERP_PRODUCT_IMAGE on EKOMERP_PRODUCT (IMAGE_ID)^
-- end EKOMERP_PRODUCT
-- begin EKOMERP_CATEGORY
alter table EKOMERP_CATEGORY add constraint FK_EKOMERP_CATEGORY_PARENT_CATEGORY foreign key (PARENT_CATEGORY_ID) references EKOMERP_CATEGORY(ID)^
create index IDX_EKOMERP_CATEGORY_PARENT_CATEGORY on EKOMERP_CATEGORY (PARENT_CATEGORY_ID)^
-- end EKOMERP_CATEGORY
-- begin EKOMERP_LABORIOUSNESS
alter table EKOMERP_LABORIOUSNESS add constraint FK_EKOMERP_LABORIOUSNESS_PRODUCT foreign key (PRODUCT_ID) references EKOMERP_PRODUCT(ID)^
alter table EKOMERP_LABORIOUSNESS add constraint FK_EKOMERP_LABORIOUSNESS_OPERATION foreign key (OPERATION_ID) references EKOMERP_OPERATION(ID)^
create index IDX_EKOMERP_LABORIOUSNESS_OPERATION on EKOMERP_LABORIOUSNESS (OPERATION_ID)^
create index IDX_EKOMERP_LABORIOUSNESS_PRODUCT on EKOMERP_LABORIOUSNESS (PRODUCT_ID)^
-- end EKOMERP_LABORIOUSNESS
-- begin EKOMERP_CONSUMPTION
alter table EKOMERP_CONSUMPTION add constraint FK_EKOMERP_CONSUMPTION_PRODUCT foreign key (PRODUCT_ID) references EKOMERP_PRODUCT(ID)^
alter table EKOMERP_CONSUMPTION add constraint FK_EKOMERP_CONSUMPTION_CONSUMABLE_PRODUCT foreign key (CONSUMABLE_PRODUCT_ID) references EKOMERP_PRODUCT(ID)^
create index IDX_EKOMERP_CONSUMPTION_CONSUMABLE_PRODUCT on EKOMERP_CONSUMPTION (CONSUMABLE_PRODUCT_ID)^
create index IDX_EKOMERP_CONSUMPTION_PRODUCT on EKOMERP_CONSUMPTION (PRODUCT_ID)^
-- end EKOMERP_CONSUMPTION
-- begin EKOMERP_LOCATION
alter table EKOMERP_LOCATION add constraint FK_EKOMERP_LOCATION_STOCKMAN foreign key (STOCKMAN_ID) references SEC_USER(ID)^
create index IDX_EKOMERP_LOCATION_STOCKMAN on EKOMERP_LOCATION (STOCKMAN_ID)^
-- end EKOMERP_LOCATION
-- begin EKOMERP_STOCK_MOVEMENT
alter table EKOMERP_STOCK_MOVEMENT add constraint FK_EKOMERP_STOCK_MOVEMENT_LOCATION foreign key (LOCATION_ID) references EKOMERP_LOCATION(ID)^
create index IDX_EKOMERP_STOCK_MOVEMENT_LOCATION on EKOMERP_STOCK_MOVEMENT (LOCATION_ID)^
-- end EKOMERP_STOCK_MOVEMENT
-- begin EKOMERP_STOCK_MOVEMENT_LINE
alter table EKOMERP_STOCK_MOVEMENT_LINE add constraint FK_EKOMERP_STOCK_MOVEMENT_LINE_PRODUCT foreign key (PRODUCT_ID) references EKOMERP_PRODUCT(ID)^
alter table EKOMERP_STOCK_MOVEMENT_LINE add constraint FK_EKOMERP_STOCK_MOVEMENT_LINE_STOCK_MOVEMENT foreign key (STOCK_MOVEMENT_ID) references EKOMERP_STOCK_MOVEMENT(ID)^
create index IDX_EKOMERP_STOCK_MOVEMENT_LINE_STOCK_MOVEMENT on EKOMERP_STOCK_MOVEMENT_LINE (STOCK_MOVEMENT_ID)^
create index IDX_EKOMERP_STOCK_MOVEMENT_LINE_PRODUCT on EKOMERP_STOCK_MOVEMENT_LINE (PRODUCT_ID)^
-- end EKOMERP_STOCK_MOVEMENT_LINE
-- begin EKOMERP_INVENTORY_QUANTITY
alter table EKOMERP_INVENTORY_QUANTITY add constraint FK_EKOMERP_INVENTORY_QUANTITY_LOCATION foreign key (LOCATION_ID) references EKOMERP_LOCATION(ID)^
alter table EKOMERP_INVENTORY_QUANTITY add constraint FK_EKOMERP_INVENTORY_QUANTITY_PRODUCT foreign key (PRODUCT_ID) references EKOMERP_PRODUCT(ID)^
create index IDX_EKOMERP_INVENTORY_QUANTITY_LOCATION on EKOMERP_INVENTORY_QUANTITY (LOCATION_ID)^
create index IDX_EKOMERP_INVENTORY_QUANTITY_PRODUCT on EKOMERP_INVENTORY_QUANTITY (PRODUCT_ID)^
-- end EKOMERP_INVENTORY_QUANTITY
